Resolved clippy warnings
SpaceManiac/discord-rs pull request #146
Opened 2017-07-27 07:19 UTC by legolord208

Note: This does not fix cyclomatic complexity and #[inline(always)] warnings.
Neither does it fix [large enum variants](https://github.com/rust-lang-nursery/rust-clippy/wiki#large_enum_variant), because compatibility.
I want the last thing fixed some day though.

2017-07-27 18:56 UTC, SpaceManiac requested changes

2017-07-27 18:56 UTC, SpaceManiac commented on src/connection.rs
> +			.spawn(move || keepalive(heartbeat_interval, sender, &mut rx)));
What's going on with these changes? What clippy lint is being claimed here?

2017-07-27 18:56 UTC, SpaceManiac commented on src/lib.rs
> +//! The Discord API can be divided into three main components: the `RESTful` API
Incorrect

2017-07-27 18:56 UTC, SpaceManiac commented on src/voice.rs
> +fn voice_thread(channel: &mut mpsc::Receiver<Status>) {
Bunch of stuff here that's also weird about the `mpsc::Receiver`?

2017-07-27 19:00 UTC, legolord208 commented on src/connection.rs
> +			.spawn(move || keepalive(heartbeat_interval, sender, &mut rx)));
Clippy says it doesn't need to be a pass by value

2017-07-27 19:00 UTC, legolord208 commented on src/lib.rs
> +//! The Discord API can be divided into three main components: the `RESTful` API
Ok. Will revert later

2017-07-31 09:05 UTC, SpaceManiac commented on src/connection.rs
> +			.spawn(move || keepalive(heartbeat_interval, sender, &mut rx)));
I want them to be, exclude this (and the other `mpsc::Receiver` changes) and everything else should be good.

2017-07-31 09:18 UTC, legolord208 commented
bump @SpaceManiac

2017-07-31 09:18 UTC, legolord208 commented
nevermind sorry, didn't see you replied to the thingy

2017-07-31 09:32 UTC, SpaceManiac commented
Fix #146

2017-07-31 09:32 UTC, closed without merging